In [1]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5,3))
B = np.random.random((3,2))
np.dot(A,B)

array([[1.31412838, 0.55565091],
       [1.25964371, 0.61932611],
       [0.93231322, 0.41361058],
       [0.59789749, 0.34945761],
       [1.11373119, 0.62143666]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.arange(10)
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


9, 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Z**Z: 가능

2 << Z >> 2: 가능

Z <- Z: 가능

1j*Z: 가능

Z/1/1: 가능

Z<Z>Z: 불가능


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan, error, array([-9.22337204e+18])

In [ ]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print('Z1:',Z1)
print('Z2:',Z2)
print(np.intersect1d(Z1,Z2))

Z1: [1 9 3 0 8 5 2 9 0 0]
Z2: [6 5 3 8 6 6 6 6 3 1]
[1 3 5 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipython-input-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [2]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [3]:
A = np.random.uniform(0,10,10)
print(A)
print(A - A%1)
print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[2.02012269 3.29014751 7.57730665 8.66617902 8.13467595 4.92185557
 3.18854505 2.60444069 3.9742952  5.62193299]
[2. 3. 7. 8. 8. 4. 3. 2. 3. 5.]
[2. 3. 7. 8. 8. 4. 3. 2. 3. 5.]
[2. 3. 7. 8. 8. 4. 3. 2. 3. 5.]
[2 3 7 8 8 4 3 2 3 5]
[2. 3. 7. 8. 8. 4. 3. 2. 3. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [4]:
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [7]:
A = np.random.random(10)
A.sort()
print(A)

[0.01771701 0.06393692 0.13786214 0.26636236 0.36762454 0.45686351
 0.59877552 0.63759918 0.64228745 0.94300648]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
A = np.random.random((10,2))
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.84997033 0.34866896 0.80904876 0.44442417 1.05101975 0.63493254
 0.3101427  0.62718478 0.37880401 0.78582206]
[1.52892741 0.90426036 1.14595773 0.43082223 1.13655942 0.16897208
 1.05548485 0.90477239 1.16819455 0.36272372]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.05947974 0.40696748 0.07816407 0.40841798 0.71026143 0.21117243
 0.06499364 0.2032545  0.5841046  0.31108469]
[0.05947974 0.40696748 0.07816407 0.40841798 0.         0.21117243
 0.06499364 0.2032545  0.5841046  0.31108469]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)

print(Z)
print(v)

print(np.abs(Z-v))
print(np.abs(Z-v).argmin())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
46.23546298214604
[46.23546298 45.23546298 44.23546298 43.23546298 42.23546298 41.23546298
 40.23546298 39.23546298 38.23546298 37.23546298 36.23546298 35.23546298
 34.23546298 33.23546298 32.23546298 31.23546298 30.23546298 29.23546298
 28.23546298 27.23546298 26.23546298 25.23546298 24.23546298 23.23546298
 22.23546298 21.23546298 20.23546298 19.23546298 18.23546298 17.23546298
 16.23546298 15.23546298 14.23546298 13.23546298 12.23546298 11.23546298
 10.23546298  9.23546298  8.23546298  7.23546298  6.23546298  5.23546298
  4.23546298  3.23546298  2.23546298  1.23546298  0.23546298  0.76453702
  1.76453702  2.76453702  3.76453702  4.76453702  5.76453702  6.76453702
  7.76453702  8.764

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [8]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [10]:
n = 10
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),3)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [11]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[7 7 1]
 [9 3 4]
 [4 9 5]]
[[4 9 5]
 [7 7 1]
 [9 3 4]]


In [12]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[7 7 1]
 [9 3 4]
 [4 9 5]]
[[9 3 4]
 [7 7 1]
 [4 9 5]]


In [13]:
# column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[7 7 1]
 [9 3 4]
 [4 9 5]]
[[7 7 1]
 [9 3 4]
 [4 9 5]]
