# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print('NumPy version:', np.__version__)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.array([1,2,3,4,5])
print(array.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array1 = np.zeros(10)
array1[4] = 1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
array2 = np.arange(start = 10,stop = 50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
array = np.array([1,2,3,4,5])
print(np.sort(array)[::-1])

[5 4 3 2 1]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array3 = np.array([1,2,0,0,4,0])
indices = np.arange(len(array3))[array3 != 0]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [13]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [14]:
array4 = np.random.random((3,3,3))
print(array4)

[[[0.14789938 0.08495124 0.09279523]
  [0.88686891 0.36437824 0.96718261]
  [0.17068731 0.58235288 0.87881094]]

 [[0.03407509 0.77610147 0.69587506]
  [0.81681527 0.92246678 0.21370554]
  [0.39339655 0.53387695 0.7808469 ]]

 [[0.3139334  0.23086401 0.23853792]
  [0.41893924 0.24346403 0.93028441]
  [0.16176934 0.99558531 0.33413734]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [15]:
array5 = np.random.random((10,10))
print(array5)
print('최솟값:',np.min(array5))
print('최댓값:',np.max(array5))

[[0.51740371 0.450571   0.60652949 0.01392847 0.71521911 0.15108384
  0.76655318 0.49362357 0.25108135 0.02885655]
 [0.04083227 0.34271833 0.92142493 0.82591273 0.27655397 0.25412092
  0.6813689  0.03859049 0.4536823  0.61643049]
 [0.32479237 0.88009658 0.3053389  0.69926907 0.09984381 0.45382248
  0.26166374 0.67012529 0.76848546 0.86085617]
 [0.22103599 0.73671542 0.10785586 0.06253526 0.25161547 0.52843817
  0.07097916 0.96058938 0.3049053  0.41472722]
 [0.83870835 0.19780668 0.94126722 0.39270075 0.58107091 0.5505754
  0.63731569 0.07957944 0.72562342 0.52804336]
 [0.55251255 0.74387178 0.64520879 0.62823133 0.89449921 0.99975189
  0.84688823 0.0897851  0.80286226 0.63511635]
 [0.88462746 0.71022797 0.13414039 0.03881211 0.7581356  0.17736307
  0.29443677 0.80364629 0.28275802 0.61826986]
 [0.09312139 0.97007995 0.15985055 0.1332254  0.65811259 0.15352011
  0.18912836 0.43966621 0.12730468 0.80583729]
 [0.50996614 0.3988497  0.89644325 0.94872476 0.70877535 0.46674965
  0.8252818  

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [16]:
array6 = np.random.random(30)
print(array6)
print('평균:',np.mean(array6))

[0.75043713 0.9407651  0.44074528 0.06472465 0.35083499 0.46573737
 0.88685274 0.1852223  0.13487837 0.19459743 0.31470407 0.60905201
 0.96616162 0.40751029 0.60469237 0.83661432 0.598555   0.28792528
 0.12538861 0.59381766 0.06269238 0.94453035 0.71739766 0.67205631
 0.23557256 0.54257802 0.34955198 0.70421778 0.7548984  0.46854993]
평균: 0.5070420662053079


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
array7 = np.ones(25).reshape(5,5)
array7[1:-1,1:-1] = 0
print(array7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [18]:
mat1 = np.zeros(25).reshape(5,5)
mat1[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
print(mat1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
mat2 = np.zeros(64).reshape(8,8)
mat2[::2,1::2] = 1
mat2[1::2, ::2] = 1
print(mat2)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [21]:
array8 = np.unravel_index(100,(6,7,8))
print(np.array(array8))

[1 5 4]


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [22]:
array9 = np.random.random((5,5))
mat3 = (array9 - np.mean(array9))/np.std(array9)
print(array9)
print(mat3)

[[0.36750895 0.20783889 0.46617915 0.54241025 0.76808715]
 [0.10561163 0.69801594 0.93335077 0.78487564 0.47685353]
 [0.6910864  0.66299986 0.23303469 0.55947335 0.46326674]
 [0.37275159 0.94380268 0.39178876 0.36290405 0.53424594]
 [0.93550361 0.20335644 0.46961348 0.94267462 0.05147593]]
[[-0.61357452 -1.22880824 -0.2333828   0.06034754  0.92991594]
 [-1.62270584  0.6599206   1.56670252  0.9946046  -0.19225274]
 [ 0.63322     0.52499819 -1.13172488  0.12609435 -0.24460475]
 [-0.59337381  1.60697534 -0.52002059 -0.6313179   0.02888918]
 [ 1.57499775 -1.24607979 -0.22014979  1.60262879 -1.83129915]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [23]:
color_dtype = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
